#!/usr/bin/env node
//
// Regenerate the IOP Design System derivatives committed under
// packages/ui-bundle/src/css/ from the real DS packages installed alongside
// this script (see README.md for why the DS itself never enters the pnpm
// workspace).
//
// Three derivatives, all mechanically extracted — nothing here is authored by
// hand:
//
//   ids-components.css   the component stylesheets listed in
//                         src/css/ids-components.yml, pulled verbatim (then
//                         reformatted for a readable diff — see
//                         prettifyCss) from @inditex/sewingiopdsweb-react-
//                         components. Built FIRST: whatever --ids-* tokens
//                         these files reference feed into the token scan
//                         below, same as every other stylesheet in src/css.
//
//   ids-tokens.css        the --ids-* and --comp-* custom property
//                         declarations that packages/ui-bundle/src/css/**/*.css
//                         (including the freshly generated
//                         ids-components.css) actually reference via
//                         var(--ids-...)/var(--comp-...), pulled from
//                         @inditex/sewingiopdsweb-styles's variables/,
//                         typography.css, motion.css and zindex.css,
//                         preserving whatever selector (:root,
//                         .ids-theme-dark, .ids-scale-large, an @media
//                         block, ...) each declaration lived under.
//
//   ids-breakpoints.css  the @custom-media declarations actually referenced
//                         via (--ids-breakpoints-...) in a @media query,
//                         pulled from variables/breakpoints.css.
//
// A declaration that is itself `var(--ids-something-else)` pulls in
// --ids-something-else too (one level is enough for every value seen in this
// package's CSS today; walkDecls below repeats until nothing new is found,
// so deeper chains are handled without changing this comment).
//
// Not every var(--ids-...) reference in a vendored component file resolves to
// a static declaration in the styles package: some DS tokens are injected at
// runtime by React with no default, always referenced with a CSS fallback
// (var(--ids-header-reserved-end-space, 0px)), and some are declared inside
// the component's own stylesheet rather than the shared token layer
// (--ids-list-item-tree-indent in list/list-item.css). Both count as
// satisfied — see unsatisfiedTokens below — only a bare, undeclared,
// fallback-less reference fails the build.
//
// Usage:
//   node sync.mjs            regenerate the derivatives and ids.lock.json
//   node sync.mjs --check     regenerate in memory, diff against what's
//                             committed, exit non-zero on drift, write nothing
//
// Both modes need `pnpm install` to have run in this directory first — this
// script reads only from ./node_modules, it never touches the network.

import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import yaml from 'js-yaml'
import postcss from 'postcss'

const require = createRequire(import.meta.url)
const here = dirname(fileURLToPath(import.meta.url))

const UI_BUNDLE_CSS = join(here, '../../packages/ui-bundle/src/css')
const COMPONENTS_MANIFEST = join(UI_BUNDLE_CSS, 'ids-components.yml')
const OUT_COMPONENTS = join(UI_BUNDLE_CSS, 'ids-components.css')
const OUT_TOKENS = join(UI_BUNDLE_CSS, 'ids-tokens.css')
const OUT_BREAKPOINTS = join(UI_BUNDLE_CSS, 'ids-breakpoints.css')
const OUT_LOCK = join(UI_BUNDLE_CSS, 'ids.lock.json')

// Source files read from @inditex/sewingiopdsweb-styles for the token layer.
// Deliberately not mixins/index.css: nothing in packages/ui-bundle/src/css
// uses a `@mixin ids-...` today (verified by the scan below — if that ever
// changes, add the relevant source file here and it starts getting scanned).
const TOKEN_SOURCES = ['variables/index.css', 'typography.css', 'motion.css', 'zindex.css']
const BREAKPOINTS_SOURCE = 'variables/breakpoints.css'

const STYLES_PKG = '@inditex/sewingiopdsweb-styles'
const COMPONENTS_PKG = '@inditex/sewingiopdsweb-react-components'

// The vast majority of what this script vendors is --ids-* (the shared
// design token layer), but some component CSS reads a second family,
// --comp-* (currently just grid-layout's --comp-grid-margin-*, the
// per-breakpoint container gutter) — declared in the same TOKEN_SOURCES
// files, just under a different prefix. Both are "a DS custom property this
// script knows how to trace back to a source declaration"; every place that
// used to hardcode --ids- now goes through these two.
const DS_PROP_RX = /^--(?:ids|comp)-/
const DS_VAR_REF_RX = /var\((--(?:ids|comp)-[a-z0-9-]+)/g

const HEADER = (sources) => `/*
 * Generated by tools/ids/sync.mjs from ${STYLES_PKG}@${dsVersion(STYLES_PKG)}.
 * Do not edit by hand — edits are overwritten by the next sync.
 *
 * Contains only the declarations packages/ui-bundle/src/css actually
 * references. Regenerate: \`just ids-sync\` (needs \`just ids-install\` first).
 * See tools/ids/README.md.
 *
 * Sources: ${sources.join(', ')}
 */
`

const COMPONENTS_HEADER = () => `/*
 * Generated by tools/ids/sync.mjs from ${COMPONENTS_PKG}@${dsVersion(COMPONENTS_PKG)},
 * per src/css/ids-components.yml. Do not edit by hand — edits are
 * overwritten by the next sync. Reformatted from the package's minified
 * source for a readable diff on a design system version bump; declarations
 * are otherwise untouched.
 *
 * Adding a component: add a line to ids-components.yml, then \`just
 * ids-sync\`. See tools/ids/README.md and
 * .opencode/skills/iop-ds-components/SKILL.md.
 */
`

function dsPath(pkg, rel) {
  return require.resolve(`${pkg}/${rel}`, { paths: [here] })
}

function dsVersion(pkg) {
  // sewingiopdsweb-styles's `exports` map is `./*.css`/`./*.json`-only and
  // does not grant `./package.json` — its main entry resolves instead, and
  // package.json always sits next to it. sewingiopdsweb-react-components
  // does grant `./package.json` directly (its `./*.json` pattern matches),
  // but resolving both packages the same defensive way keeps this one
  // function correct regardless of which export shape a future DS version
  // ships.
  let entry
  try {
    entry = require.resolve(`${pkg}/package.json`, { paths: [here] })
  } catch {
    entry = require.resolve(pkg, { paths: [here] })
  }
  return require(entry.endsWith('.json') ? entry : join(dirname(entry), 'package.json')).version
}

async function readSource(rel) {
  const path = dsPath(STYLES_PKG, rel)
  const content = await readFile(path, 'utf8')
  return { rel, path, content }
}

function sha256(content) {
  return createHash('sha256').update(content).digest('hex')
}

// postcss's own Node#cleanRaws() resets formatting to its stringifier
// default, which indents 4 spaces per nesting level; halved here to match
// this bundle's 2-space CSS. Safe for any nesting depth: every run of
// leading spaces is a multiple of 4 by construction, so halving in place
// can't collide with content.
function prettifyCss(content) {
  const root = postcss.parse(content)
  root.cleanRaws()
  return root
    .toString()
    .replace(/^ +/gm, (spaces) => ' '.repeat(spaces.length / 2))
    .trim()
}

// Reads the manifest and returns, per listed file, its resolved path and
// (prettified) content plus the relative path used in its header comment —
// in manifest order, which is also emission order.
async function readComponents() {
  const manifestYaml = await readFile(COMPONENTS_MANIFEST, 'utf8')
  const manifest = yaml.load(manifestYaml) ?? {}
  const files = []
  for (const [dir, leaves] of Object.entries(manifest.components ?? {})) {
    for (const leaf of leaves) {
      const rel = `${dir}/${leaf}`
      const path = dsPath(COMPONENTS_PKG, rel)
      const raw = await readFile(path, 'utf8')
      files.push({ rel, path, raw, pretty: prettifyCss(raw) })
    }
  }
  return { manifestYaml, files }
}

// Every custom property referenced via var(--ids-...) across src/css, plus
// every (--ids-breakpoints-...) named inside a media query. `extraContent` is
// the freshly generated ids-components.css, scanned in memory rather than off
// disk so a token a newly-added component references is picked up in the same
// run that adds it, and --check never depends on a possibly-stale committed
// copy of that same file.
async function scanUsed(extraContent) {
  // Minimal recursive glob — the css tree is flat enough not to need a dep.
  const { readdirSync, statSync } = await import('node:fs')
  const files = []
  ;(function walk(dir) {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name)
      if (statSync(path).isDirectory()) walk(path)
      else if (
        name.endsWith('.css') &&
        !name.startsWith('ids-tokens') &&
        !name.startsWith('ids-breakpoints') &&
        !name.startsWith('ids-components')
      )
        files.push(path)
    }
  })(UI_BUNDLE_CSS)

  const tokens = new Set()
  const breakpoints = new Set()
  const scan = (content) => {
    for (const m of content.matchAll(DS_VAR_REF_RX)) tokens.add(m[1])
    for (const m of content.matchAll(/\(--ids-breakpoints-[a-z0-9-]+\)/g)) breakpoints.add(m[0].slice(1, -1))
  }
  for (const file of files) scan(await readFile(file, 'utf8'))
  scan(extraContent)
  return { tokens, breakpoints }
}

// A token referenced with a CSS fallback (var(--ids-x, default)) is always
// satisfied, whatever the styles package does or doesn't declare — the
// fallback is what actually renders when the package doesn't supply it. A
// token declared inside the vendored component CSS itself (rather than the
// shared token layer) is satisfied too. Returns the set of wanted tokens that
// are neither of those AND not emitted by extractTokens — i.e. actually
// missing.
function unsatisfiedTokens(wanted, emitted, componentsCss) {
  const hasFallback = new Set()
  for (const m of componentsCss.matchAll(/var\((--(?:ids|comp)-[a-z0-9-]+)\s*,/g)) hasFallback.add(m[1])
  const declaredInComponents = new Set()
  postcss.parse(componentsCss).walkDecls((decl) => {
    if (DS_PROP_RX.test(decl.prop)) declaredInComponents.add(decl.prop)
  })
  const emittedProps = new Set([...emitted.values()].flatMap((b) => [...b.decls.keys()]))
  return [...wanted].filter((t) => !emittedProps.has(t) && !hasFallback.has(t) && !declaredInComponents.has(t))
}

// Parses each source, keeps only rules with at least one kept declaration,
// and within a kept rule keeps only declarations whose prop is in `wanted`
// (mutated in place as referenced properties are discovered — a kept
// declaration's value may itself contain one or more `var(--ids-...)`, not
// necessarily as the whole value, e.g. `--ids-motion-micro-states: all
// var(--ids-motion-duration-s) var(--ids-motion-easing-standard-1)`; every
// `--ids-*` named inside any kept value is added to `wanted` so its own
// declaration gets picked up too — looped to a fixed point so it doesn't
// matter which source defines which property first).
function extractTokens(sources, wanted) {
  const emittedBySelector = new Map() // selector text -> Map(prop -> {decl text, atRuleParams|null})
  let changed = true
  while (changed) {
    changed = false
    for (const { content } of sources) {
      const root = postcss.parse(content)
      root.walkRules((rule) => {
        const atRuleParams = rule.parent?.type === 'atrule' ? `${rule.parent.name} ${rule.parent.params}` : null
        rule.walkDecls((decl) => {
          if (!DS_PROP_RX.test(decl.prop)) return
          if (!wanted.has(decl.prop)) return
          const key = `${atRuleParams ?? ''}::${rule.selector}`
          if (!emittedBySelector.has(key))
            emittedBySelector.set(key, { atRuleParams, selector: rule.selector, decls: new Map() })
          const bucket = emittedBySelector.get(key)
          if (!bucket.decls.has(decl.prop)) {
            bucket.decls.set(decl.prop, `${decl.prop}: ${decl.value}`)
            changed = true
          }
          for (const m of decl.value.matchAll(DS_VAR_REF_RX)) {
            if (!wanted.has(m[1])) {
              wanted.add(m[1])
              changed = true
            }
          }
        })
      })
    }
  }
  return emittedBySelector
}

function renderTokens(emittedBySelector) {
  // Group consecutive-in-source-order buckets is unnecessary; stable output
  // order is: no-at-rule buckets first (by first-seen selector), then
  // at-rule buckets grouped by their @media params.
  const plain = []
  const byAtRule = new Map()
  for (const bucket of emittedBySelector.values()) {
    if (bucket.decls.size === 0) continue
    if (!bucket.atRuleParams) plain.push(bucket)
    else {
      if (!byAtRule.has(bucket.atRuleParams)) byAtRule.set(bucket.atRuleParams, [])
      byAtRule.get(bucket.atRuleParams).push(bucket)
    }
  }
  const renderRule = (bucket) =>
    `${bucket.selector} {\n${[...bucket.decls.values()].map((d) => `  ${d};`).join('\n')}\n}`
  let out = plain.map(renderRule).join('\n\n')
  for (const [atRuleParams, buckets] of byAtRule) {
    out += `\n\n@${atRuleParams} {\n${buckets.map(renderRule).join('\n').replaceAll('\n', '\n  ')}\n}`
  }
  return out.trim() + '\n'
}

function extractBreakpoints(content, wanted) {
  const root = postcss.parse(content)
  const kept = []
  root.walkAtRules('custom-media', (atRule) => {
    const name = atRule.params.trim().split(/\s+/)[0]
    if (wanted.has(name)) kept.push(`@custom-media ${atRule.params};`)
  })
  return kept
}

async function main() {
  const check = process.argv.includes('--check')

  const { manifestYaml, files: componentFiles } = await readComponents()
  const componentsCss =
    componentFiles.length === 0
      ? ''
      : COMPONENTS_HEADER() +
        '\n' +
        componentFiles.map((f) => `/* ${COMPONENTS_PKG}/${f.rel} */\n${f.pretty}`).join('\n\n') +
        '\n'

  const { tokens: wantedTokens, breakpoints: wantedBreakpoints } = await scanUsed(componentsCss)

  const tokenSources = await Promise.all(TOKEN_SOURCES.map(readSource))
  const breakpointsSource = await readSource(BREAKPOINTS_SOURCE)

  const emitted = extractTokens(tokenSources, wantedTokens)
  const tokensCss = HEADER(TOKEN_SOURCES) + '\n' + renderTokens(emitted)

  const breakpointLines = extractBreakpoints(breakpointsSource.content, wantedBreakpoints)
  const missingBreakpoints = [...wantedBreakpoints].filter((b) => !breakpointLines.some((l) => l.includes(`${b} `)))
  if (missingBreakpoints.length) {
    console.error(
      `sync.mjs: breakpoint(s) referenced in src/css but not found in ${BREAKPOINTS_SOURCE}: ${missingBreakpoints.join(', ')}`
    )
    process.exitCode = 1
    return
  }
  const breakpointsCss = HEADER([BREAKPOINTS_SOURCE]) + '\n' + breakpointLines.join('\n') + '\n'

  const missingTokens = unsatisfiedTokens(wantedTokens, emitted, componentsCss)
  if (missingTokens.length) {
    console.error(`sync.mjs: token(s) referenced in src/css but not found in any source: ${missingTokens.join(', ')}`)
    process.exitCode = 1
    return
  }

  const lock = {
    designSystemVersion: dsVersion(STYLES_PKG),
    componentsPackageVersion: dsVersion(COMPONENTS_PKG),
    generatedAt: new Date().toISOString(),
    sources: Object.fromEntries([...tokenSources, breakpointsSource].map((s) => [s.rel, sha256(s.content)])),
    components: Object.fromEntries(componentFiles.map((f) => [f.rel, sha256(f.raw)])),
    componentsManifest: sha256(manifestYaml),
    emittedTokens: [...wantedTokens].sort(),
    emittedBreakpoints: [...wantedBreakpoints].sort(),
  }

  if (check) {
    const [currentComponents, currentTokens, currentBreakpoints, currentLock] = await Promise.all([
      readFile(OUT_COMPONENTS, 'utf8').catch(() => null),
      readFile(OUT_TOKENS, 'utf8').catch(() => null),
      readFile(OUT_BREAKPOINTS, 'utf8').catch(() => null),
      readFile(OUT_LOCK, 'utf8').catch(() => null),
    ])
    const drift = []
    if ((currentComponents ?? '') !== componentsCss) drift.push('ids-components.css')
    if (currentTokens !== tokensCss) drift.push('ids-tokens.css')
    if (currentBreakpoints !== breakpointsCss) drift.push('ids-breakpoints.css')
    if (
      currentLock === null ||
      JSON.parse(currentLock).designSystemVersion !== lock.designSystemVersion ||
      JSON.parse(currentLock).componentsPackageVersion !== lock.componentsPackageVersion ||
      JSON.parse(currentLock).componentsManifest !== lock.componentsManifest
    )
      drift.push('ids.lock.json (version or manifest)')
    if (drift.length) {
      console.error(
        `sync.mjs --check: drift detected in ${drift.join(', ')}. Run 'just ids-sync' and commit the result.`
      )
      process.exitCode = 1
    } else {
      console.log('sync.mjs --check: up to date.')
    }
    return
  }

  await writeFile(OUT_COMPONENTS, componentsCss)
  await writeFile(OUT_TOKENS, tokensCss)
  await writeFile(OUT_BREAKPOINTS, breakpointsCss)
  await writeFile(OUT_LOCK, JSON.stringify(lock, null, 2) + '\n')
  console.log(
    `sync.mjs: wrote ${OUT_COMPONENTS} (${componentFiles.length} file(s)), ${OUT_TOKENS}, ${OUT_BREAKPOINTS}, ` +
      `${OUT_LOCK} (DS ${lock.designSystemVersion}, ${lock.emittedTokens.length} tokens, ` +
      `${lock.emittedBreakpoints.length} breakpoints).`
  )
}

main()
