#!/usr/bin/env node
//
// Regenerate the IOP Design System derivatives committed under
// packages/ui-bundle/src/css/ from the real DS package installed alongside
// this script (see README.md for why the DS itself never enters the pnpm
// workspace).
//
// Two derivatives, both mechanically extracted — nothing here is authored by
// hand:
//
//   ids-tokens.css       the --ids-* custom property declarations that
//                         packages/ui-bundle/src/css/**/*.css actually
//                         reference via var(--ids-...), pulled from
//                         @inditex/sewingiopdsweb-styles's variables/,
//                         motion.css and zindex.css, preserving whatever
//                         selector (:root, .ids-theme-dark, .ids-scale-large,
//                         an @media block, ...) each declaration lived under.
//
//   ids-breakpoints.css  the @custom-media declarations actually referenced
//                         via (--ids-breakpoints-*) in a @media query,
//                         pulled from variables/breakpoints.css.
//
// A declaration that is itself `var(--ids-something-else)` pulls in
// --ids-something-else too (one level is enough for every value seen in this
// package's CSS today; walkDecls below repeats until nothing new is found,
// so deeper chains are handled without changing this comment).
//
// Usage:
//   node sync.mjs            regenerate the derivatives and ids.lock.json
//   node sync.mjs --check     regenerate in memory, diff against what's
//                             committed, exit non-zero on drift, write nothing
//
// Both modes need `pnpm install` to have run in this directory first — this
// script reads only from ./node_modules, it never touches the network.

import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import postcss from 'postcss'

const require = createRequire(import.meta.url)
const here = dirname(fileURLToPath(import.meta.url))

const UI_BUNDLE_CSS = join(here, '../../packages/ui-bundle/src/css')
const OUT_TOKENS = join(UI_BUNDLE_CSS, 'ids-tokens.css')
const OUT_BREAKPOINTS = join(UI_BUNDLE_CSS, 'ids-breakpoints.css')
const OUT_LOCK = join(UI_BUNDLE_CSS, 'ids.lock.json')

// Source files read from the DS package. Deliberately not typography.css or
// mixins/index.css: nothing in packages/ui-bundle/src/css uses a typography
// shorthand token or a `@mixin ids-...` today (verified by the scan below —
// if that ever changes, add the relevant source file here and it starts
// getting scanned).
const TOKEN_SOURCES = ['variables/index.css', 'motion.css', 'zindex.css']
const BREAKPOINTS_SOURCE = 'variables/breakpoints.css'

const HEADER = (sources) => `/*
 * Generated by tools/ids/sync.mjs from @inditex/sewingiopdsweb-styles@${dsVersion()}.
 * Do not edit by hand — edits are overwritten by the next sync.
 *
 * Contains only the declarations packages/ui-bundle/src/css actually
 * references. Regenerate: \`just ids-sync\` (needs \`just ids-install\` first).
 * See tools/ids/README.md.
 *
 * Sources: ${sources.join(', ')}
 */
`

function dsPath(rel) {
  return require.resolve(`@inditex/sewingiopdsweb-styles/${rel}`, { paths: [here] })
}

function dsVersion() {
  // Not require.resolve('.../package.json') — the package's `exports` map
  // doesn't grant that subpath. Its main entry does resolve, and package.json
  // always sits next to it.
  const entry = require.resolve('@inditex/sewingiopdsweb-styles', { paths: [here] })
  return require(join(dirname(entry), 'package.json')).version
}

async function readSource(rel) {
  const path = dsPath(rel)
  const content = await readFile(path, 'utf8')
  return { rel, path, content }
}

function sha256(content) {
  return createHash('sha256').update(content).digest('hex')
}

// Every custom property this file's own CSS reads via var(--ids-...), plus
// every (--ids-breakpoints-...) named inside a media query.
async function scanUsed() {
  // Minimal recursive glob — the css tree is flat enough not to need a dep.
  const { readdirSync, statSync } = await import('node:fs')
  const files = []
  ;(function walk(dir) {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name)
      if (statSync(path).isDirectory()) walk(path)
      else if (name.endsWith('.css') && !name.startsWith('ids-tokens') && !name.startsWith('ids-breakpoints'))
        files.push(path)
    }
  })(UI_BUNDLE_CSS)

  const tokens = new Set()
  const breakpoints = new Set()
  for (const file of files) {
    const content = await readFile(file, 'utf8')
    for (const m of content.matchAll(/var\((--ids-[a-z0-9-]+)/g)) tokens.add(m[1])
    for (const m of content.matchAll(/\(--ids-breakpoints-[a-z0-9-]+\)/g)) breakpoints.add(m[0].slice(1, -1))
  }
  return { tokens, breakpoints }
}

// Parses each source, keeps only rules with at least one kept declaration,
// and within a kept rule keeps only declarations whose prop is in `wanted`
// (mutated in place as referenced properties are discovered — a kept
// declaration's value may itself contain one or more `var(--ids-...)`, not
// necessarily as the whole value, e.g. `--ids-motion-micro-states: all
// var(--ids-motion-duration-s) var(--ids-motion-easing-standard-1)`; every
// `--ids-*` named inside any kept value is added to `wanted` so its own
// declaration gets picked up too — looped to a fixed point so it doesn't
// matter which source defines which property first).
function extractTokens(sources, wanted) {
  const emittedBySelector = new Map() // selector text -> Map(prop -> {decl text, atRuleParams|null})
  let changed = true
  while (changed) {
    changed = false
    for (const { content } of sources) {
      const root = postcss.parse(content)
      root.walkRules((rule) => {
        const atRuleParams = rule.parent?.type === 'atrule' ? `${rule.parent.name} ${rule.parent.params}` : null
        rule.walkDecls((decl) => {
          if (!decl.prop.startsWith('--ids-')) return
          if (!wanted.has(decl.prop)) return
          const key = `${atRuleParams ?? ''}::${rule.selector}`
          if (!emittedBySelector.has(key))
            emittedBySelector.set(key, { atRuleParams, selector: rule.selector, decls: new Map() })
          const bucket = emittedBySelector.get(key)
          if (!bucket.decls.has(decl.prop)) {
            bucket.decls.set(decl.prop, `${decl.prop}: ${decl.value}`)
            changed = true
          }
          for (const m of decl.value.matchAll(/var\((--ids-[a-z0-9-]+)/g)) {
            if (!wanted.has(m[1])) {
              wanted.add(m[1])
              changed = true
            }
          }
        })
      })
    }
  }
  return emittedBySelector
}

function renderTokens(emittedBySelector) {
  // Group consecutive-in-source-order buckets is unnecessary; stable output
  // order is: no-at-rule buckets first (by first-seen selector), then
  // at-rule buckets grouped by their @media params.
  const plain = []
  const byAtRule = new Map()
  for (const bucket of emittedBySelector.values()) {
    if (bucket.decls.size === 0) continue
    if (!bucket.atRuleParams) plain.push(bucket)
    else {
      if (!byAtRule.has(bucket.atRuleParams)) byAtRule.set(bucket.atRuleParams, [])
      byAtRule.get(bucket.atRuleParams).push(bucket)
    }
  }
  const renderRule = (bucket) =>
    `${bucket.selector} {\n${[...bucket.decls.values()].map((d) => `  ${d};`).join('\n')}\n}`
  let out = plain.map(renderRule).join('\n\n')
  for (const [atRuleParams, buckets] of byAtRule) {
    out += `\n\n@${atRuleParams} {\n${buckets.map(renderRule).join('\n').replaceAll('\n', '\n  ')}\n}`
  }
  return out.trim() + '\n'
}

function extractBreakpoints(content, wanted) {
  const root = postcss.parse(content)
  const kept = []
  root.walkAtRules('custom-media', (atRule) => {
    const name = atRule.params.trim().split(/\s+/)[0]
    if (wanted.has(name)) kept.push(`@custom-media ${atRule.params};`)
  })
  return kept
}

async function main() {
  const check = process.argv.includes('--check')
  const { tokens: wantedTokens, breakpoints: wantedBreakpoints } = await scanUsed()

  const tokenSources = await Promise.all(TOKEN_SOURCES.map(readSource))
  const breakpointsSource = await readSource(BREAKPOINTS_SOURCE)

  const emitted = extractTokens(tokenSources, wantedTokens)
  const tokensCss = HEADER(TOKEN_SOURCES) + '\n' + renderTokens(emitted)

  const breakpointLines = extractBreakpoints(breakpointsSource.content, wantedBreakpoints)
  const missingBreakpoints = [...wantedBreakpoints].filter((b) => !breakpointLines.some((l) => l.includes(`${b} `)))
  if (missingBreakpoints.length) {
    console.error(
      `sync.mjs: breakpoint(s) referenced in src/css but not found in ${BREAKPOINTS_SOURCE}: ${missingBreakpoints.join(', ')}`
    )
    process.exitCode = 1
    return
  }
  const breakpointsCss = HEADER([BREAKPOINTS_SOURCE]) + '\n' + breakpointLines.join('\n') + '\n'

  const missingTokens = [...wantedTokens].filter((t) => ![...emitted.values()].some((b) => b.decls.has(t)))
  if (missingTokens.length) {
    console.error(`sync.mjs: token(s) referenced in src/css but not found in any source: ${missingTokens.join(', ')}`)
    process.exitCode = 1
    return
  }

  const lock = {
    designSystemVersion: dsVersion(),
    generatedAt: new Date().toISOString(),
    sources: Object.fromEntries([...tokenSources, breakpointsSource].map((s) => [s.rel, sha256(s.content)])),
    emittedTokens: [...wantedTokens].sort(),
    emittedBreakpoints: [...wantedBreakpoints].sort(),
  }

  if (check) {
    const [currentTokens, currentBreakpoints, currentLock] = await Promise.all([
      readFile(OUT_TOKENS, 'utf8').catch(() => null),
      readFile(OUT_BREAKPOINTS, 'utf8').catch(() => null),
      readFile(OUT_LOCK, 'utf8').catch(() => null),
    ])
    const drift = []
    if (currentTokens !== tokensCss) drift.push('ids-tokens.css')
    if (currentBreakpoints !== breakpointsCss) drift.push('ids-breakpoints.css')
    if (currentLock === null || JSON.parse(currentLock).designSystemVersion !== lock.designSystemVersion)
      drift.push('ids.lock.json (version)')
    if (drift.length) {
      console.error(
        `sync.mjs --check: drift detected in ${drift.join(', ')}. Run 'just ids-sync' and commit the result.`
      )
      process.exitCode = 1
    } else {
      console.log('sync.mjs --check: up to date.')
    }
    return
  }

  await writeFile(OUT_TOKENS, tokensCss)
  await writeFile(OUT_BREAKPOINTS, breakpointsCss)
  await writeFile(OUT_LOCK, JSON.stringify(lock, null, 2) + '\n')
  console.log(
    `sync.mjs: wrote ${OUT_TOKENS}, ${OUT_BREAKPOINTS}, ${OUT_LOCK} (DS ${lock.designSystemVersion}, ${lock.emittedTokens.length} tokens, ${lock.emittedBreakpoints.length} breakpoints).`
  )
}

main()
